[package]
name = "dbscan-serving"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.5"
prost = "0.8"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
linfa-clustering = "0.4.0"
linfa = "0.4.0"
ndarray = { version = "0.14", features = ["serde", "approx"] }
ndarray-rand = "0.14.0"
rand_isaac = "0.3.0"
plotters = "0.3.1"
approx = "0.5.0"
# dbscan = { git = "https://github.com/savish/dbscan" }

[build-dependencies]
tonic-build = "0.5"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[[bin]]
name = "testlinfa"
path = "src/testlinfa.rs"
